#!/bin/bash

set -ev # Ref https://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps

case "${1:?}" in
    before_install)
        ## Travis CI does not support rebar3 yet. See https://github.com/travis-ci/travis-ci/issues/6506#issuecomment-275189490
        Rebar3="${2:?}"
        curl -f -L -o "${Rebar3:?}" https://github.com/erlang/rebar3/releases/download/3.3.5/rebar3
        chmod +x "${Rebar3:?}"
        ;;
    install)
        Rebar3="${2:?}"
        "${Rebar3:?}" deps
        "${Rebar3:?}" dialyzer -u true -s false
        ;;
    script)
        Rebar3="${2:?}"
        "${Rebar3:?}" ct
        ;;
esac
